name: nutripic
description: "Nutripic App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  kakao_flutter_sdk_user: ^1.9.6
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/foods/
  fonts:
      - family: Pretendard
        fonts:
            - asset: assets/fonts/Pretendard-Thin.otf
              weight: 100
            - asset: assets/fonts/Pretendard-ExtraLight.otf
              weight: 200
            - asset: assets/fonts/Pretendard-Light.otf
              weight: 300
            - asset: assets/fonts/Pretendard-Regular.otf
              weight: 400
            - asset: assets/fonts/Pretendard-Medium.otf
              weight: 500
            - asset: assets/fonts/Pretendard-SemiBold.otf
              weight: 600
            - asset: assets/fonts/Pretendard-Bold.otf
              weight: 700
            - asset: assets/fonts/Pretendard-ExtraBold.otf
              weight: 800
            - asset: assets/fonts/Pretendard-Black.otf
              weight: 900
